
include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  exclude:
    - "bin/cache/**"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.mocks.dart"
    - "**/generated/**"
    - "*.config.dart"