name: wakefully_analyzer
description: ""
publish_to: "none"

version: 2.0.8+37

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^8.1.3
  injectable: ^2.3.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  dartz: ^0.10.1
  firebase_auth: ^4.7.2
  firebase_auth_platform_interface: ^7.3.0
  firebase_core: ^2.14.0
  formz: ^0.7.0
  json_annotation: ^4.8.1
  hydrated_bloc: ^9.1.2
  path_provider: ^2.0.15
  google_fonts: ^6.2.1
  sizer: ^2.0.15
  flutter_svg: ^2.0.7
  keyboard_dismisser: ^3.0.0
  url_launcher: ^6.1.12
  blobs: ^2.0.0
  collection: ^1.17.1
  retrofit: ^4.0.1
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1
  flutter_spinkit: ^5.2.0
  video_player: ^2.7.0
  animated_text_kit: ^4.2.2
  speech_to_text: ^6.3.0
  avatar_glow: ^3.0.1
  highlight_text: ^1.6.0
  share_plus: ^9.0.0
  package_info_plus: ^8.0.0
  purchases_flutter: ^6.29.2
  logger: ^2.0.1
  wakelock_plus: ^1.1.1
  styled_text: ^8.1.0
  pub_semver: ^2.1.4
  flutter_branch_sdk: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.5
  injectable_generator: ^2.4.0
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  retrofit_generator: ^8.1.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
